### ISSUE TITLE
ERROR :: Failed to load/process image: GdkPixbuf image load error - Couldn’t recognize the image file format for file

### ISSUE THREAD

**Issue by Flurrywinde** [mk-fg/infinite-image-scroller#6]
Does `infinite-image-scroller` still work for you after yesterday's Arch update? I get the above error message and the window remains transparent. It was working fine the day before.

**Comment by mk-fg** [comment]
Yeah, seem to work. Just ran `pacman -Syu` and tested afterwards - no such issues, with regular jpg's at least.
Do you get this with some specific file formats (something less common like .webp maybe?), or specific images?
Also, I have libjpeg-turbo here, which I think gtk should use for its jpg-loading, maybe the issue is with different libjpeg implementation?

**Comment by Flurrywinde** [comment]
It was with just regular jpg's. I think the issue is because I use the Fish shell *and* have `snapd` installed. I suspect it was the snapd update that broke things. (It also broke `gnome-terminal`. LOL.) It seems it's that $XDG_DATA_DIRS no longer has the defaults (/usr/share and /usr/local/share), and putting them back got infinite-image-scroller working again.

I couldn't find anything online about this issue, but for other Fish (and Snap) users out there, I added this to my fish config file:
```
set -gx --path XDG_DATA_DIRS /usr/local/share:/usr/share:/usr/lib/kitty/shell-integration:/var/lib/snapd/desktop
```

**Comment by mk-fg** [comment]
Sounds like a bug in snapd.
I don't have it here, but flatpak does similar thing via /etc/profile.d/flatpak.sh, but of course adds to $XDG_DATA_DIRS, not just overrides those, it seems, while presumably snapd script managed to do the latter, which definitely looks like it might be a bug in such profile.d script.

**Comment by Flurrywinde** [comment]
Yup, definitely a bug in snapd. They issued an update today addressing the Fish shell and $XDG_DATA_DIRS in particular, but it didn't fix the problem on my particular system yet. I had to put back my workaround.
